version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
    - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: always
  app:
    build: .
    environment:
      DB_HOST: db
      DB_NAME: notesdb
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: notesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
volumes:
  postgres_data: